### ISSUE TITLE
Problem with the library typing

### ISSUE THREAD

**Issue by Mezosky** [dccuchile/wefe#12]
I tried to test the wefe library through colabolatory and it does not work due to compatibility issues with the library typing (product colab works with python 3.7). I got this problem:

```python
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

Perhaps a solution to this problem is to add the following lines in the code:

```python
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
```

**Comment by pbadillatorrealba** [comment]
Hello @Mezosky ,

Sorry for the problems!
I will try to include it as soon as possible.

Best regards, 
Pablo.

**Comment by pbadillatorrealba** [comment]
Hello, 

I have just fixed the error you indicate. 
Sorry for the long delay.

To update WEFE with pip:

```
pip install -U wefe
```

To update with conda:

```bash
conda install -c pbadilla wefe 
```


Best regards, 
Pablo.
